//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XML_WS_AgencyApp.MyRemoteServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ftn-booking.com/agentEndpoint", ConfigurationName="MyRemoteServices.AgentEndpointPort")]
    public interface AgentEndpointPort {
        
        // CODEGEN: Generating message contract since the operation addBookingUnit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinchronizationObject))]
        XML_WS_AgencyApp.MyRemoteServices.addBookingUnitResponse1 addBookingUnit(XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.addBookingUnitResponse1> addBookingUnitAsync(XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest1 request);
        
        // CODEGEN: Generating message contract since the operation cancelReservation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinchronizationObject))]
        XML_WS_AgencyApp.MyRemoteServices.cancelReservationResponse1 cancelReservation(XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.cancelReservationResponse1> cancelReservationAsync(XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation addLocalReservation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinchronizationObject))]
        XML_WS_AgencyApp.MyRemoteServices.addLocalReservationResponse1 addLocalReservation(XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.addLocalReservationResponse1> addLocalReservationAsync(XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation sendMessage is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinchronizationObject))]
        XML_WS_AgencyApp.MyRemoteServices.sendMessageResponse1 sendMessage(XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.sendMessageResponse1> sendMessageAsync(XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest1 request);
        
        // CODEGEN: Generating message contract since the operation confirmReservation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinchronizationObject))]
        XML_WS_AgencyApp.MyRemoteServices.confirmReservationResponse1 confirmReservation(XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.confirmReservationResponse1> confirmReservationAsync(XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest1 request);
        
        // CODEGEN: Generating message contract since the operation agentLogin is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinchronizationObject))]
        XML_WS_AgencyApp.MyRemoteServices.agentLoginResponse1 agentLogin(XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.agentLoginResponse1> agentLoginAsync(XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest1 request);
        
        // CODEGEN: Generating message contract since the operation manageMonthlyPrices is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SinchronizationObject))]
        XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesResponse1 manageMonthlyPrices(XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesResponse1> manageMonthlyPricesAsync(XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class addBookingUnitRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BookingUnit bookingUnitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BookingUnit bookingUnit {
            get {
                return this.bookingUnitField;
            }
            set {
                this.bookingUnitField = value;
                this.RaisePropertyChanged("bookingUnit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class BookingUnit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long cityMainServerIdField;
        
        private string addressField;
        
        private string descriptionField;
        
        private int peopleNoField;
        
        private long agentMainServerIdField;
        
        private long accTypeMainServerIdField;
        
        private long accCategoryMainServerIdField;
        
        private long[] bonusFeaturesMainServerIdsField;
        
        private hMapStringStringElement[] base64ImagesListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long cityMainServerId {
            get {
                return this.cityMainServerIdField;
            }
            set {
                this.cityMainServerIdField = value;
                this.RaisePropertyChanged("cityMainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int peopleNo {
            get {
                return this.peopleNoField;
            }
            set {
                this.peopleNoField = value;
                this.RaisePropertyChanged("peopleNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long agentMainServerId {
            get {
                return this.agentMainServerIdField;
            }
            set {
                this.agentMainServerIdField = value;
                this.RaisePropertyChanged("agentMainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long accTypeMainServerId {
            get {
                return this.accTypeMainServerIdField;
            }
            set {
                this.accTypeMainServerIdField = value;
                this.RaisePropertyChanged("accTypeMainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long accCategoryMainServerId {
            get {
                return this.accCategoryMainServerIdField;
            }
            set {
                this.accCategoryMainServerIdField = value;
                this.RaisePropertyChanged("accCategoryMainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bonusFeaturesMainServerIds", Order=8)]
        public long[] bonusFeaturesMainServerIds {
            get {
                return this.bonusFeaturesMainServerIdsField;
            }
            set {
                this.bonusFeaturesMainServerIdsField = value;
                this.RaisePropertyChanged("bonusFeaturesMainServerIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("base64ImagesList", Order=9)]
        public hMapStringStringElement[] base64ImagesList {
            get {
                return this.base64ImagesListField;
            }
            set {
                this.base64ImagesListField = value;
                this.RaisePropertyChanged("base64ImagesList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class hMapStringStringElement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class SinchronizationObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AccomodationType[] accTypesListField;
        
        private AccomodationCategory[] accCatsListField;
        
        private BonusFeature[] bonusFeaturesListField;
        
        private Country[] countriesListField;
        
        private City[] citiesListField;
        
        private RegUsrMessage[] regUserMessagesListField;
        
        private MainServerReservation[] reservationsListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accTypesList", Order=0)]
        public AccomodationType[] accTypesList {
            get {
                return this.accTypesListField;
            }
            set {
                this.accTypesListField = value;
                this.RaisePropertyChanged("accTypesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accCatsList", Order=1)]
        public AccomodationCategory[] accCatsList {
            get {
                return this.accCatsListField;
            }
            set {
                this.accCatsListField = value;
                this.RaisePropertyChanged("accCatsList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bonusFeaturesList", Order=2)]
        public BonusFeature[] bonusFeaturesList {
            get {
                return this.bonusFeaturesListField;
            }
            set {
                this.bonusFeaturesListField = value;
                this.RaisePropertyChanged("bonusFeaturesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("countriesList", Order=3)]
        public Country[] countriesList {
            get {
                return this.countriesListField;
            }
            set {
                this.countriesListField = value;
                this.RaisePropertyChanged("countriesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("citiesList", Order=4)]
        public City[] citiesList {
            get {
                return this.citiesListField;
            }
            set {
                this.citiesListField = value;
                this.RaisePropertyChanged("citiesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regUserMessagesList", Order=5)]
        public RegUsrMessage[] regUserMessagesList {
            get {
                return this.regUserMessagesListField;
            }
            set {
                this.regUserMessagesListField = value;
                this.RaisePropertyChanged("regUserMessagesList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reservationsList", Order=6)]
        public MainServerReservation[] reservationsList {
            get {
                return this.reservationsListField;
            }
            set {
                this.reservationsListField = value;
                this.RaisePropertyChanged("reservationsList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class AccomodationType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long mainServerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long mainServerId {
            get {
                return this.mainServerIdField;
            }
            set {
                this.mainServerIdField = value;
                this.RaisePropertyChanged("mainServerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class AccomodationCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long mainServerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long mainServerId {
            get {
                return this.mainServerIdField;
            }
            set {
                this.mainServerIdField = value;
                this.RaisePropertyChanged("mainServerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class BonusFeature : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long mainServerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long mainServerId {
            get {
                return this.mainServerIdField;
            }
            set {
                this.mainServerIdField = value;
                this.RaisePropertyChanged("mainServerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class Country : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private long mainServerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long mainServerId {
            get {
                return this.mainServerIdField;
            }
            set {
                this.mainServerIdField = value;
                this.RaisePropertyChanged("mainServerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class City : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string postalCodeField;
        
        private long mainServerIdField;
        
        private Country countryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string postalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("postalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long mainServerId {
            get {
                return this.mainServerIdField;
            }
            set {
                this.mainServerIdField = value;
                this.RaisePropertyChanged("mainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Country country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class RegUsrMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long mainServerIdField;
        
        private string contentField;
        
        private RegisteredUserInfo regUsrInfoField;
        
        private long agentUserMainServerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mainServerId {
            get {
                return this.mainServerIdField;
            }
            set {
                this.mainServerIdField = value;
                this.RaisePropertyChanged("mainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public RegisteredUserInfo regUsrInfo {
            get {
                return this.regUsrInfoField;
            }
            set {
                this.regUsrInfoField = value;
                this.RaisePropertyChanged("regUsrInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long agentUserMainServerId {
            get {
                return this.agentUserMainServerIdField;
            }
            set {
                this.agentUserMainServerIdField = value;
                this.RaisePropertyChanged("agentUserMainServerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class RegisteredUserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long mainServerIdField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mainServerId {
            get {
                return this.mainServerIdField;
            }
            set {
                this.mainServerIdField = value;
                this.RaisePropertyChanged("mainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class MainServerReservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long mainServerIdField;
        
        private System.DateTime fromField;
        
        private System.DateTime toField;
        
        private double totalPriceField;
        
        private ReservationStatus reservationStatusField;
        
        private string subjectNameField;
        
        private string subjectSurnameField;
        
        private long bookingUnitMainServerIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mainServerId {
            get {
                return this.mainServerIdField;
            }
            set {
                this.mainServerIdField = value;
                this.RaisePropertyChanged("mainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime from {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime to {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double totalPrice {
            get {
                return this.totalPriceField;
            }
            set {
                this.totalPriceField = value;
                this.RaisePropertyChanged("totalPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ReservationStatus reservationStatus {
            get {
                return this.reservationStatusField;
            }
            set {
                this.reservationStatusField = value;
                this.RaisePropertyChanged("reservationStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string subjectName {
            get {
                return this.subjectNameField;
            }
            set {
                this.subjectNameField = value;
                this.RaisePropertyChanged("subjectName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string subjectSurname {
            get {
                return this.subjectSurnameField;
            }
            set {
                this.subjectSurnameField = value;
                this.RaisePropertyChanged("subjectSurname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long bookingUnitMainServerId {
            get {
                return this.bookingUnitMainServerIdField;
            }
            set {
                this.bookingUnitMainServerIdField = value;
                this.RaisePropertyChanged("bookingUnitMainServerId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public enum ReservationStatus {
        
        /// <remarks/>
        WAITING,
        
        /// <remarks/>
        CONFIRMED,
        
        /// <remarks/>
        CANCELED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class ReservationLite : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long reservationMainServerIdField;
        
        private ReservationStatus reservationStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long reservationMainServerId {
            get {
                return this.reservationMainServerIdField;
            }
            set {
                this.reservationMainServerIdField = value;
                this.RaisePropertyChanged("reservationMainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReservationStatus reservationStatus {
            get {
                return this.reservationStatusField;
            }
            set {
                this.reservationStatusField = value;
                this.RaisePropertyChanged("reservationStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class Message : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long senderAgentMainServerIdField;
        
        private long receiverUserMainServerIdField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long senderAgentMainServerId {
            get {
                return this.senderAgentMainServerIdField;
            }
            set {
                this.senderAgentMainServerIdField = value;
                this.RaisePropertyChanged("senderAgentMainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long receiverUserMainServerId {
            get {
                return this.receiverUserMainServerIdField;
            }
            set {
                this.receiverUserMainServerIdField = value;
                this.RaisePropertyChanged("receiverUserMainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
                this.RaisePropertyChanged("content");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class Reservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long bookingUnitMainServerIdField;
        
        private string reserveeFirstNameField;
        
        private string reserveeLastNameField;
        
        private string dateFromField;
        
        private string dateToField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long bookingUnitMainServerId {
            get {
                return this.bookingUnitMainServerIdField;
            }
            set {
                this.bookingUnitMainServerIdField = value;
                this.RaisePropertyChanged("bookingUnitMainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string reserveeFirstName {
            get {
                return this.reserveeFirstNameField;
            }
            set {
                this.reserveeFirstNameField = value;
                this.RaisePropertyChanged("reserveeFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string reserveeLastName {
            get {
                return this.reserveeLastNameField;
            }
            set {
                this.reserveeLastNameField = value;
                this.RaisePropertyChanged("reserveeLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string dateFrom {
            get {
                return this.dateFromField;
            }
            set {
                this.dateFromField = value;
                this.RaisePropertyChanged("dateFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string dateTo {
            get {
                return this.dateToField;
            }
            set {
                this.dateToField = value;
                this.RaisePropertyChanged("dateTo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class MonthlyPrices : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long mainServerIdField;
        
        private int yearField;
        
        private double[] monthlyPricesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long mainServerId {
            get {
                return this.mainServerIdField;
            }
            set {
                this.mainServerIdField = value;
                this.RaisePropertyChanged("mainServerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("monthlyPrices", Order=2)]
        public double[] monthlyPrices {
            get {
                return this.monthlyPricesField;
            }
            set {
                this.monthlyPricesField = value;
                this.RaisePropertyChanged("monthlyPrices");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class ResponseWrapper : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private object responseBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object responseBody {
            get {
                return this.responseBodyField;
            }
            set {
                this.responseBodyField = value;
                this.RaisePropertyChanged("responseBody");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class addBookingUnitResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWrapper responseWrapperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseWrapper responseWrapper {
            get {
                return this.responseWrapperField;
            }
            set {
                this.responseWrapperField = value;
                this.RaisePropertyChanged("responseWrapper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBookingUnitRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest addBookingUnitRequest;
        
        public addBookingUnitRequest1() {
        }
        
        public addBookingUnitRequest1(XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest addBookingUnitRequest) {
            this.addBookingUnitRequest = addBookingUnitRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addBookingUnitResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.addBookingUnitResponse addBookingUnitResponse;
        
        public addBookingUnitResponse1() {
        }
        
        public addBookingUnitResponse1(XML_WS_AgencyApp.MyRemoteServices.addBookingUnitResponse addBookingUnitResponse) {
            this.addBookingUnitResponse = addBookingUnitResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class cancelReservationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReservationLite reservationLiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReservationLite reservationLite {
            get {
                return this.reservationLiteField;
            }
            set {
                this.reservationLiteField = value;
                this.RaisePropertyChanged("reservationLite");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class cancelReservationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWrapper responseWrapperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseWrapper responseWrapper {
            get {
                return this.responseWrapperField;
            }
            set {
                this.responseWrapperField = value;
                this.RaisePropertyChanged("responseWrapper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelReservationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest cancelReservationRequest;
        
        public cancelReservationRequest1() {
        }
        
        public cancelReservationRequest1(XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest cancelReservationRequest) {
            this.cancelReservationRequest = cancelReservationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelReservationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.cancelReservationResponse cancelReservationResponse;
        
        public cancelReservationResponse1() {
        }
        
        public cancelReservationResponse1(XML_WS_AgencyApp.MyRemoteServices.cancelReservationResponse cancelReservationResponse) {
            this.cancelReservationResponse = cancelReservationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class addLocalReservationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Reservation localReservationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Reservation localReservation {
            get {
                return this.localReservationField;
            }
            set {
                this.localReservationField = value;
                this.RaisePropertyChanged("localReservation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class addLocalReservationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWrapper responseWrapperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseWrapper responseWrapper {
            get {
                return this.responseWrapperField;
            }
            set {
                this.responseWrapperField = value;
                this.RaisePropertyChanged("responseWrapper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addLocalReservationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest addLocalReservationRequest;
        
        public addLocalReservationRequest1() {
        }
        
        public addLocalReservationRequest1(XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest addLocalReservationRequest) {
            this.addLocalReservationRequest = addLocalReservationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addLocalReservationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.addLocalReservationResponse addLocalReservationResponse;
        
        public addLocalReservationResponse1() {
        }
        
        public addLocalReservationResponse1(XML_WS_AgencyApp.MyRemoteServices.addLocalReservationResponse addLocalReservationResponse) {
            this.addLocalReservationResponse = addLocalReservationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class sendMessageRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Message messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Message message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class sendMessageResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWrapper responseWrapperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseWrapper responseWrapper {
            get {
                return this.responseWrapperField;
            }
            set {
                this.responseWrapperField = value;
                this.RaisePropertyChanged("responseWrapper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest sendMessageRequest;
        
        public sendMessageRequest1() {
        }
        
        public sendMessageRequest1(XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest sendMessageRequest) {
            this.sendMessageRequest = sendMessageRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendMessageResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.sendMessageResponse sendMessageResponse;
        
        public sendMessageResponse1() {
        }
        
        public sendMessageResponse1(XML_WS_AgencyApp.MyRemoteServices.sendMessageResponse sendMessageResponse) {
            this.sendMessageResponse = sendMessageResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class confirmReservationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReservationLite reservationLiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReservationLite reservationLite {
            get {
                return this.reservationLiteField;
            }
            set {
                this.reservationLiteField = value;
                this.RaisePropertyChanged("reservationLite");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class confirmReservationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWrapper responseWrapperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseWrapper responseWrapper {
            get {
                return this.responseWrapperField;
            }
            set {
                this.responseWrapperField = value;
                this.RaisePropertyChanged("responseWrapper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class confirmReservationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest confirmReservationRequest;
        
        public confirmReservationRequest1() {
        }
        
        public confirmReservationRequest1(XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest confirmReservationRequest) {
            this.confirmReservationRequest = confirmReservationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class confirmReservationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.confirmReservationResponse confirmReservationResponse;
        
        public confirmReservationResponse1() {
        }
        
        public confirmReservationResponse1(XML_WS_AgencyApp.MyRemoteServices.confirmReservationResponse confirmReservationResponse) {
            this.confirmReservationResponse = confirmReservationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class agentLoginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class agentLoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWrapper responseWrapperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseWrapper responseWrapper {
            get {
                return this.responseWrapperField;
            }
            set {
                this.responseWrapperField = value;
                this.RaisePropertyChanged("responseWrapper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agentLoginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest agentLoginRequest;
        
        public agentLoginRequest1() {
        }
        
        public agentLoginRequest1(XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest agentLoginRequest) {
            this.agentLoginRequest = agentLoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class agentLoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.agentLoginResponse agentLoginResponse;
        
        public agentLoginResponse1() {
        }
        
        public agentLoginResponse1(XML_WS_AgencyApp.MyRemoteServices.agentLoginResponse agentLoginResponse) {
            this.agentLoginResponse = agentLoginResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class manageMonthlyPricesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MonthlyPrices monthlyPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MonthlyPrices monthlyPrice {
            get {
                return this.monthlyPriceField;
            }
            set {
                this.monthlyPriceField = value;
                this.RaisePropertyChanged("monthlyPrice");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ftn-booking.com/agentEndpoint")]
    public partial class manageMonthlyPricesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResponseWrapper responseWrapperField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseWrapper responseWrapper {
            get {
                return this.responseWrapperField;
            }
            set {
                this.responseWrapperField = value;
                this.RaisePropertyChanged("responseWrapper");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class manageMonthlyPricesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest manageMonthlyPricesRequest;
        
        public manageMonthlyPricesRequest1() {
        }
        
        public manageMonthlyPricesRequest1(XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest manageMonthlyPricesRequest) {
            this.manageMonthlyPricesRequest = manageMonthlyPricesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class manageMonthlyPricesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ftn-booking.com/agentEndpoint", Order=0)]
        public XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesResponse manageMonthlyPricesResponse;
        
        public manageMonthlyPricesResponse1() {
        }
        
        public manageMonthlyPricesResponse1(XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesResponse manageMonthlyPricesResponse) {
            this.manageMonthlyPricesResponse = manageMonthlyPricesResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgentEndpointPortChannel : XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgentEndpointPortClient : System.ServiceModel.ClientBase<XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort>, XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort {
        
        public AgentEndpointPortClient() {
        }
        
        public AgentEndpointPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgentEndpointPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentEndpointPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgentEndpointPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_WS_AgencyApp.MyRemoteServices.addBookingUnitResponse1 XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.addBookingUnit(XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest1 request) {
            return base.Channel.addBookingUnit(request);
        }
        
        public XML_WS_AgencyApp.MyRemoteServices.addBookingUnitResponse addBookingUnit(XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest addBookingUnitRequest) {
            XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest1();
            inValue.addBookingUnitRequest = addBookingUnitRequest;
            XML_WS_AgencyApp.MyRemoteServices.addBookingUnitResponse1 retVal = ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).addBookingUnit(inValue);
            return retVal.addBookingUnitResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.addBookingUnitResponse1> XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.addBookingUnitAsync(XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest1 request) {
            return base.Channel.addBookingUnitAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.addBookingUnitResponse1> addBookingUnitAsync(XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest addBookingUnitRequest) {
            XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.addBookingUnitRequest1();
            inValue.addBookingUnitRequest = addBookingUnitRequest;
            return ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).addBookingUnitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_WS_AgencyApp.MyRemoteServices.cancelReservationResponse1 XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.cancelReservation(XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest1 request) {
            return base.Channel.cancelReservation(request);
        }
        
        public XML_WS_AgencyApp.MyRemoteServices.cancelReservationResponse cancelReservation(XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest cancelReservationRequest) {
            XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest1();
            inValue.cancelReservationRequest = cancelReservationRequest;
            XML_WS_AgencyApp.MyRemoteServices.cancelReservationResponse1 retVal = ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).cancelReservation(inValue);
            return retVal.cancelReservationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.cancelReservationResponse1> XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.cancelReservationAsync(XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest1 request) {
            return base.Channel.cancelReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.cancelReservationResponse1> cancelReservationAsync(XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest cancelReservationRequest) {
            XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.cancelReservationRequest1();
            inValue.cancelReservationRequest = cancelReservationRequest;
            return ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).cancelReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_WS_AgencyApp.MyRemoteServices.addLocalReservationResponse1 XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.addLocalReservation(XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest1 request) {
            return base.Channel.addLocalReservation(request);
        }
        
        public XML_WS_AgencyApp.MyRemoteServices.addLocalReservationResponse addLocalReservation(XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest addLocalReservationRequest) {
            XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest1();
            inValue.addLocalReservationRequest = addLocalReservationRequest;
            XML_WS_AgencyApp.MyRemoteServices.addLocalReservationResponse1 retVal = ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).addLocalReservation(inValue);
            return retVal.addLocalReservationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.addLocalReservationResponse1> XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.addLocalReservationAsync(XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest1 request) {
            return base.Channel.addLocalReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.addLocalReservationResponse1> addLocalReservationAsync(XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest addLocalReservationRequest) {
            XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.addLocalReservationRequest1();
            inValue.addLocalReservationRequest = addLocalReservationRequest;
            return ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).addLocalReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_WS_AgencyApp.MyRemoteServices.sendMessageResponse1 XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.sendMessage(XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest1 request) {
            return base.Channel.sendMessage(request);
        }
        
        public XML_WS_AgencyApp.MyRemoteServices.sendMessageResponse sendMessage(XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest sendMessageRequest) {
            XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest1();
            inValue.sendMessageRequest = sendMessageRequest;
            XML_WS_AgencyApp.MyRemoteServices.sendMessageResponse1 retVal = ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).sendMessage(inValue);
            return retVal.sendMessageResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.sendMessageResponse1> XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.sendMessageAsync(XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest1 request) {
            return base.Channel.sendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.sendMessageResponse1> sendMessageAsync(XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest sendMessageRequest) {
            XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.sendMessageRequest1();
            inValue.sendMessageRequest = sendMessageRequest;
            return ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).sendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_WS_AgencyApp.MyRemoteServices.confirmReservationResponse1 XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.confirmReservation(XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest1 request) {
            return base.Channel.confirmReservation(request);
        }
        
        public XML_WS_AgencyApp.MyRemoteServices.confirmReservationResponse confirmReservation(XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest confirmReservationRequest) {
            XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest1();
            inValue.confirmReservationRequest = confirmReservationRequest;
            XML_WS_AgencyApp.MyRemoteServices.confirmReservationResponse1 retVal = ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).confirmReservation(inValue);
            return retVal.confirmReservationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.confirmReservationResponse1> XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.confirmReservationAsync(XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest1 request) {
            return base.Channel.confirmReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.confirmReservationResponse1> confirmReservationAsync(XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest confirmReservationRequest) {
            XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.confirmReservationRequest1();
            inValue.confirmReservationRequest = confirmReservationRequest;
            return ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).confirmReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_WS_AgencyApp.MyRemoteServices.agentLoginResponse1 XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.agentLogin(XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest1 request) {
            return base.Channel.agentLogin(request);
        }
        
        public XML_WS_AgencyApp.MyRemoteServices.agentLoginResponse agentLogin(XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest agentLoginRequest) {
            XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest1();
            inValue.agentLoginRequest = agentLoginRequest;
            XML_WS_AgencyApp.MyRemoteServices.agentLoginResponse1 retVal = ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).agentLogin(inValue);
            return retVal.agentLoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.agentLoginResponse1> XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.agentLoginAsync(XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest1 request) {
            return base.Channel.agentLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.agentLoginResponse1> agentLoginAsync(XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest agentLoginRequest) {
            XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.agentLoginRequest1();
            inValue.agentLoginRequest = agentLoginRequest;
            return ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).agentLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesResponse1 XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.manageMonthlyPrices(XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest1 request) {
            return base.Channel.manageMonthlyPrices(request);
        }
        
        public XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesResponse manageMonthlyPrices(XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest manageMonthlyPricesRequest) {
            XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest1();
            inValue.manageMonthlyPricesRequest = manageMonthlyPricesRequest;
            XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesResponse1 retVal = ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).manageMonthlyPrices(inValue);
            return retVal.manageMonthlyPricesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesResponse1> XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort.manageMonthlyPricesAsync(XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest1 request) {
            return base.Channel.manageMonthlyPricesAsync(request);
        }
        
        public System.Threading.Tasks.Task<XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesResponse1> manageMonthlyPricesAsync(XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest manageMonthlyPricesRequest) {
            XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest1 inValue = new XML_WS_AgencyApp.MyRemoteServices.manageMonthlyPricesRequest1();
            inValue.manageMonthlyPricesRequest = manageMonthlyPricesRequest;
            return ((XML_WS_AgencyApp.MyRemoteServices.AgentEndpointPort)(this)).manageMonthlyPricesAsync(inValue);
        }
    }
}
